DROP TABLE IF EXISTS place_amenities;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS amenities;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
	id	VARCHAR(36) PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email 	VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR (255) NOT NULL,
	is_admin BOOLEAN 	NOT NULL DEFAULT 0,
	created_at DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP
	updated_at DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS amenities(
	 id      VARCHAR(36) PRIMARY KEY,
	 name	VARCHAR(50) NOT NULL UNIQUE,
	created_at DATETIME NOT NULL DEFAULT  
        updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS places (
	 id      VARCHAR(36) PRIMARY KEY,
        title	VARCHAR(100) NOT NULL, 	
	description TEXT,
        price	FLOAT NOT NULL,
        latitude FLOAT NOT NULL,
	longitude FLOAT NOT NULL,
	onwer_id VARCHAR (36) NOT NULL,
        created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
        updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
	FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reviews (
	id      VARCHAR(36) PRIMARY KEY,
	text	TEXT	NOT NULL,
	rating	INTEGER	NOT NULL CHECK (rating >= 1 AND rati)
	place_id VARCHAR(36)	NOT NULL, 
	user_id	 VARCHAR(36) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT
        updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS place_amenities (
	place_id VARCHAR(36) NOT NULL,
	amenity_id VARCHAR(36) NOT NULL,
	PRIMARY KEY (place_id, amenity_id),
	FOREIGN KEY (place_id) REFERENCES places(id),
	FOREIGN KEY (amenity_id) REFERENCES amenities(id)
);
	
